// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbewbbcwffuvowxhwlqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZXdiYmN3ZmZ1dm93eGh3bHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODIxNjAsImV4cCI6MjA2MTk1ODE2MH0.q_-Sj8Imc2WGy9WcAq8-iSEe7tptMEy0mXD_Db6Wirc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);